<?php
/**
 * AuditoriaRiscoConversationScoresV2
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;

use \ArrayAccess;
use \FalaAI\ObjectSerializer;

/**
 * AuditoriaRiscoConversationScoresV2 Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AuditoriaRiscoConversationScoresV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AuditoriaRiscoConversationScoresV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'consolidated_score' => 'float',
        'violation_density_per_min' => 'float',
        'sentiment_trend' => 'mixed',
        'pct_turns_with_violation' => 'float',
        'most_critical_turn' => 'mixed',
        'positive_negative_ratio' => 'mixed',
        'global_risk_severity' => 'string',
        'global_risk_severity_label' => 'string',
        'global_risk_severity_color' => 'string',
        'risk_likelihood_avg' => 'float',
        'risk_impact_avg' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'consolidated_score' => null,
        'violation_density_per_min' => null,
        'sentiment_trend' => null,
        'pct_turns_with_violation' => null,
        'most_critical_turn' => null,
        'positive_negative_ratio' => null,
        'global_risk_severity' => null,
        'global_risk_severity_label' => null,
        'global_risk_severity_color' => null,
        'risk_likelihood_avg' => null,
        'risk_impact_avg' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'consolidated_score' => false,
        'violation_density_per_min' => false,
        'sentiment_trend' => true,
        'pct_turns_with_violation' => false,
        'most_critical_turn' => true,
        'positive_negative_ratio' => true,
        'global_risk_severity' => false,
        'global_risk_severity_label' => false,
        'global_risk_severity_color' => false,
        'risk_likelihood_avg' => false,
        'risk_impact_avg' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'consolidated_score' => 'consolidated_score',
        'violation_density_per_min' => 'violation_density_per_min',
        'sentiment_trend' => 'sentiment_trend',
        'pct_turns_with_violation' => 'pct_turns_with_violation',
        'most_critical_turn' => 'most_critical_turn',
        'positive_negative_ratio' => 'positive_negative_ratio',
        'global_risk_severity' => 'global_risk_severity',
        'global_risk_severity_label' => 'global_risk_severity_label',
        'global_risk_severity_color' => 'global_risk_severity_color',
        'risk_likelihood_avg' => 'risk_likelihood_avg',
        'risk_impact_avg' => 'risk_impact_avg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'consolidated_score' => 'setConsolidatedScore',
        'violation_density_per_min' => 'setViolationDensityPerMin',
        'sentiment_trend' => 'setSentimentTrend',
        'pct_turns_with_violation' => 'setPctTurnsWithViolation',
        'most_critical_turn' => 'setMostCriticalTurn',
        'positive_negative_ratio' => 'setPositiveNegativeRatio',
        'global_risk_severity' => 'setGlobalRiskSeverity',
        'global_risk_severity_label' => 'setGlobalRiskSeverityLabel',
        'global_risk_severity_color' => 'setGlobalRiskSeverityColor',
        'risk_likelihood_avg' => 'setRiskLikelihoodAvg',
        'risk_impact_avg' => 'setRiskImpactAvg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'consolidated_score' => 'getConsolidatedScore',
        'violation_density_per_min' => 'getViolationDensityPerMin',
        'sentiment_trend' => 'getSentimentTrend',
        'pct_turns_with_violation' => 'getPctTurnsWithViolation',
        'most_critical_turn' => 'getMostCriticalTurn',
        'positive_negative_ratio' => 'getPositiveNegativeRatio',
        'global_risk_severity' => 'getGlobalRiskSeverity',
        'global_risk_severity_label' => 'getGlobalRiskSeverityLabel',
        'global_risk_severity_color' => 'getGlobalRiskSeverityColor',
        'risk_likelihood_avg' => 'getRiskLikelihoodAvg',
        'risk_impact_avg' => 'getRiskImpactAvg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('consolidated_score', $data ?? [], null);
        $this->setIfExists('violation_density_per_min', $data ?? [], null);
        $this->setIfExists('sentiment_trend', $data ?? [], null);
        $this->setIfExists('pct_turns_with_violation', $data ?? [], null);
        $this->setIfExists('most_critical_turn', $data ?? [], null);
        $this->setIfExists('positive_negative_ratio', $data ?? [], null);
        $this->setIfExists('global_risk_severity', $data ?? [], null);
        $this->setIfExists('global_risk_severity_label', $data ?? [], null);
        $this->setIfExists('global_risk_severity_color', $data ?? [], null);
        $this->setIfExists('risk_likelihood_avg', $data ?? [], null);
        $this->setIfExists('risk_impact_avg', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets consolidated_score
     *
     * @return float|null
     */
    public function getConsolidatedScore()
    {
        return $this->container['consolidated_score'];
    }

    /**
     * Sets consolidated_score
     *
     * @param float|null $consolidated_score Consolidated score
     *
     * @return self
     */
    public function setConsolidatedScore($consolidated_score)
    {
        if (is_null($consolidated_score)) {
            throw new \InvalidArgumentException('non-nullable consolidated_score cannot be null');
        }
        $this->container['consolidated_score'] = $consolidated_score;

        return $this;
    }

    /**
     * Gets violation_density_per_min
     *
     * @return float|null
     */
    public function getViolationDensityPerMin()
    {
        return $this->container['violation_density_per_min'];
    }

    /**
     * Sets violation_density_per_min
     *
     * @param float|null $violation_density_per_min Violation density/min
     *
     * @return self
     */
    public function setViolationDensityPerMin($violation_density_per_min)
    {
        if (is_null($violation_density_per_min)) {
            throw new \InvalidArgumentException('non-nullable violation_density_per_min cannot be null');
        }
        $this->container['violation_density_per_min'] = $violation_density_per_min;

        return $this;
    }

    /**
     * Gets sentiment_trend
     *
     * @return mixed|null
     */
    public function getSentimentTrend()
    {
        return $this->container['sentiment_trend'];
    }

    /**
     * Sets sentiment_trend
     *
     * @param mixed|null $sentiment_trend Sentiment trend
     *
     * @return self
     */
    public function setSentimentTrend($sentiment_trend)
    {
        if (is_null($sentiment_trend)) {
            array_push($this->openAPINullablesSetToNull, 'sentiment_trend');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sentiment_trend', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sentiment_trend'] = $sentiment_trend;

        return $this;
    }

    /**
     * Gets pct_turns_with_violation
     *
     * @return float|null
     */
    public function getPctTurnsWithViolation()
    {
        return $this->container['pct_turns_with_violation'];
    }

    /**
     * Sets pct_turns_with_violation
     *
     * @param float|null $pct_turns_with_violation % turns with violation
     *
     * @return self
     */
    public function setPctTurnsWithViolation($pct_turns_with_violation)
    {
        if (is_null($pct_turns_with_violation)) {
            throw new \InvalidArgumentException('non-nullable pct_turns_with_violation cannot be null');
        }
        $this->container['pct_turns_with_violation'] = $pct_turns_with_violation;

        return $this;
    }

    /**
     * Gets most_critical_turn
     *
     * @return mixed|null
     */
    public function getMostCriticalTurn()
    {
        return $this->container['most_critical_turn'];
    }

    /**
     * Sets most_critical_turn
     *
     * @param mixed|null $most_critical_turn Most critical turn
     *
     * @return self
     */
    public function setMostCriticalTurn($most_critical_turn)
    {
        if (is_null($most_critical_turn)) {
            array_push($this->openAPINullablesSetToNull, 'most_critical_turn');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('most_critical_turn', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['most_critical_turn'] = $most_critical_turn;

        return $this;
    }

    /**
     * Gets positive_negative_ratio
     *
     * @return mixed|null
     */
    public function getPositiveNegativeRatio()
    {
        return $this->container['positive_negative_ratio'];
    }

    /**
     * Sets positive_negative_ratio
     *
     * @param mixed|null $positive_negative_ratio Positive:negative ratio
     *
     * @return self
     */
    public function setPositiveNegativeRatio($positive_negative_ratio)
    {
        if (is_null($positive_negative_ratio)) {
            array_push($this->openAPINullablesSetToNull, 'positive_negative_ratio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('positive_negative_ratio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['positive_negative_ratio'] = $positive_negative_ratio;

        return $this;
    }

    /**
     * Gets global_risk_severity
     *
     * @return string|null
     */
    public function getGlobalRiskSeverity()
    {
        return $this->container['global_risk_severity'];
    }

    /**
     * Sets global_risk_severity
     *
     * @param string|null $global_risk_severity Global risk severity code
     *
     * @return self
     */
    public function setGlobalRiskSeverity($global_risk_severity)
    {
        if (is_null($global_risk_severity)) {
            throw new \InvalidArgumentException('non-nullable global_risk_severity cannot be null');
        }
        $this->container['global_risk_severity'] = $global_risk_severity;

        return $this;
    }

    /**
     * Gets global_risk_severity_label
     *
     * @return string|null
     */
    public function getGlobalRiskSeverityLabel()
    {
        return $this->container['global_risk_severity_label'];
    }

    /**
     * Sets global_risk_severity_label
     *
     * @param string|null $global_risk_severity_label Global risk severity label
     *
     * @return self
     */
    public function setGlobalRiskSeverityLabel($global_risk_severity_label)
    {
        if (is_null($global_risk_severity_label)) {
            throw new \InvalidArgumentException('non-nullable global_risk_severity_label cannot be null');
        }
        $this->container['global_risk_severity_label'] = $global_risk_severity_label;

        return $this;
    }

    /**
     * Gets global_risk_severity_color
     *
     * @return string|null
     */
    public function getGlobalRiskSeverityColor()
    {
        return $this->container['global_risk_severity_color'];
    }

    /**
     * Sets global_risk_severity_color
     *
     * @param string|null $global_risk_severity_color Global risk severity color
     *
     * @return self
     */
    public function setGlobalRiskSeverityColor($global_risk_severity_color)
    {
        if (is_null($global_risk_severity_color)) {
            throw new \InvalidArgumentException('non-nullable global_risk_severity_color cannot be null');
        }
        $this->container['global_risk_severity_color'] = $global_risk_severity_color;

        return $this;
    }

    /**
     * Gets risk_likelihood_avg
     *
     * @return float|null
     */
    public function getRiskLikelihoodAvg()
    {
        return $this->container['risk_likelihood_avg'];
    }

    /**
     * Sets risk_likelihood_avg
     *
     * @param float|null $risk_likelihood_avg Risk likelihood avg
     *
     * @return self
     */
    public function setRiskLikelihoodAvg($risk_likelihood_avg)
    {
        if (is_null($risk_likelihood_avg)) {
            throw new \InvalidArgumentException('non-nullable risk_likelihood_avg cannot be null');
        }
        $this->container['risk_likelihood_avg'] = $risk_likelihood_avg;

        return $this;
    }

    /**
     * Gets risk_impact_avg
     *
     * @return float|null
     */
    public function getRiskImpactAvg()
    {
        return $this->container['risk_impact_avg'];
    }

    /**
     * Sets risk_impact_avg
     *
     * @param float|null $risk_impact_avg Risk impact avg
     *
     * @return self
     */
    public function setRiskImpactAvg($risk_impact_avg)
    {
        if (is_null($risk_impact_avg)) {
            throw new \InvalidArgumentException('non-nullable risk_impact_avg cannot be null');
        }
        $this->container['risk_impact_avg'] = $risk_impact_avg;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


