<?php
/**
 * AuditoriaRiscoDetectionsV2
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;

use \ArrayAccess;
use \FalaAI\ObjectSerializer;

/**
 * AuditoriaRiscoDetectionsV2 Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AuditoriaRiscoDetectionsV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AuditoriaRiscoDetectionsV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'violations' => '\FalaAI\Model\AuditoriaRiscoDetectionItemV2[]',
        'positives' => '\FalaAI\Model\AuditoriaRiscoDetectionItemV2[]',
        'client_risk_alerts' => 'array<string,mixed>[]',
        'client_behavior_alerts' => 'array<string,mixed>[]',
        'client_negatives' => '\FalaAI\Model\AuditoriaRiscoDetectionItemV2[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'violations' => null,
        'positives' => null,
        'client_risk_alerts' => null,
        'client_behavior_alerts' => null,
        'client_negatives' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'violations' => false,
        'positives' => false,
        'client_risk_alerts' => false,
        'client_behavior_alerts' => false,
        'client_negatives' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'violations' => 'violations',
        'positives' => 'positives',
        'client_risk_alerts' => 'client_risk_alerts',
        'client_behavior_alerts' => 'client_behavior_alerts',
        'client_negatives' => 'client_negatives'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'violations' => 'setViolations',
        'positives' => 'setPositives',
        'client_risk_alerts' => 'setClientRiskAlerts',
        'client_behavior_alerts' => 'setClientBehaviorAlerts',
        'client_negatives' => 'setClientNegatives'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'violations' => 'getViolations',
        'positives' => 'getPositives',
        'client_risk_alerts' => 'getClientRiskAlerts',
        'client_behavior_alerts' => 'getClientBehaviorAlerts',
        'client_negatives' => 'getClientNegatives'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('violations', $data ?? [], null);
        $this->setIfExists('positives', $data ?? [], null);
        $this->setIfExists('client_risk_alerts', $data ?? [], null);
        $this->setIfExists('client_behavior_alerts', $data ?? [], null);
        $this->setIfExists('client_negatives', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets violations
     *
     * @return \FalaAI\Model\AuditoriaRiscoDetectionItemV2[]|null
     */
    public function getViolations()
    {
        return $this->container['violations'];
    }

    /**
     * Sets violations
     *
     * @param \FalaAI\Model\AuditoriaRiscoDetectionItemV2[]|null $violations Active violations
     *
     * @return self
     */
    public function setViolations($violations)
    {
        if (is_null($violations)) {
            throw new \InvalidArgumentException('non-nullable violations cannot be null');
        }
        $this->container['violations'] = $violations;

        return $this;
    }

    /**
     * Gets positives
     *
     * @return \FalaAI\Model\AuditoriaRiscoDetectionItemV2[]|null
     */
    public function getPositives()
    {
        return $this->container['positives'];
    }

    /**
     * Sets positives
     *
     * @param \FalaAI\Model\AuditoriaRiscoDetectionItemV2[]|null $positives Active positives
     *
     * @return self
     */
    public function setPositives($positives)
    {
        if (is_null($positives)) {
            throw new \InvalidArgumentException('non-nullable positives cannot be null');
        }
        $this->container['positives'] = $positives;

        return $this;
    }

    /**
     * Gets client_risk_alerts
     *
     * @return array<string,mixed>[]|null
     */
    public function getClientRiskAlerts()
    {
        return $this->container['client_risk_alerts'];
    }

    /**
     * Sets client_risk_alerts
     *
     * @param array<string,mixed>[]|null $client_risk_alerts Client risk alerts
     *
     * @return self
     */
    public function setClientRiskAlerts($client_risk_alerts)
    {
        if (is_null($client_risk_alerts)) {
            throw new \InvalidArgumentException('non-nullable client_risk_alerts cannot be null');
        }
        $this->container['client_risk_alerts'] = $client_risk_alerts;

        return $this;
    }

    /**
     * Gets client_behavior_alerts
     *
     * @return array<string,mixed>[]|null
     */
    public function getClientBehaviorAlerts()
    {
        return $this->container['client_behavior_alerts'];
    }

    /**
     * Sets client_behavior_alerts
     *
     * @param array<string,mixed>[]|null $client_behavior_alerts Client behavior alerts
     *
     * @return self
     */
    public function setClientBehaviorAlerts($client_behavior_alerts)
    {
        if (is_null($client_behavior_alerts)) {
            throw new \InvalidArgumentException('non-nullable client_behavior_alerts cannot be null');
        }
        $this->container['client_behavior_alerts'] = $client_behavior_alerts;

        return $this;
    }

    /**
     * Gets client_negatives
     *
     * @return \FalaAI\Model\AuditoriaRiscoDetectionItemV2[]|null
     */
    public function getClientNegatives()
    {
        return $this->container['client_negatives'];
    }

    /**
     * Sets client_negatives
     *
     * @param \FalaAI\Model\AuditoriaRiscoDetectionItemV2[]|null $client_negatives Client negatives
     *
     * @return self
     */
    public function setClientNegatives($client_negatives)
    {
        if (is_null($client_negatives)) {
            throw new \InvalidArgumentException('non-nullable client_negatives cannot be null');
        }
        $this->container['client_negatives'] = $client_negatives;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


