<?php
/**
 * AuditoriaRiscoV2
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;

use \ArrayAccess;
use \FalaAI\ObjectSerializer;

/**
 * AuditoriaRiscoV2 Class Doc Comment
 *
 * @category Class
 * @description Response V2 (build_public_response_v2) â€” blocos logicos EN-US. Fonte: response_builder.py.
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AuditoriaRiscoV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AuditoriaRiscoV2';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'meta' => '\FalaAI\Model\AuditoriaRiscoMetaV2',
        'participants' => '\FalaAI\Model\AuditoriaRiscoParticipantsV2',
        'verdict' => '\FalaAI\Model\AuditoriaRiscoVerdictV2',
        'scores' => '\FalaAI\Model\AuditoriaRiscoScoresV2',
        'detections' => '\FalaAI\Model\AuditoriaRiscoDetectionsV2',
        'analysis' => '\FalaAI\Model\AuditoriaRiscoAnalysisV2',
        'timeline' => '\FalaAI\Model\AuditoriaRiscoTimelineV2',
        'audio_event_model' => '\FalaAI\Model\AuditoriaRiscoAudioEventModelV2',
        'categories_summary' => 'array<string,mixed>',
        'indexer' => '\FalaAI\Model\AuditoriaRiscoIndexerV2',
        'summary' => '\FalaAI\Model\AuditoriaRiscoSummaryV2',
        'acoes_i18n' => 'array<string,mixed>',
        'audit_decisions' => '\FalaAI\Model\AuditoriaRiscoAuditDecisionsV2',
        'scoring_explanation' => '\FalaAI\Model\AuditoriaRiscoScoringExplanationV2',
        'html_report' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'meta' => null,
        'participants' => null,
        'verdict' => null,
        'scores' => null,
        'detections' => null,
        'analysis' => null,
        'timeline' => null,
        'audio_event_model' => null,
        'categories_summary' => null,
        'indexer' => null,
        'summary' => null,
        'acoes_i18n' => null,
        'audit_decisions' => null,
        'scoring_explanation' => null,
        'html_report' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'meta' => false,
        'participants' => false,
        'verdict' => false,
        'scores' => false,
        'detections' => false,
        'analysis' => false,
        'timeline' => false,
        'audio_event_model' => false,
        'categories_summary' => false,
        'indexer' => false,
        'summary' => false,
        'acoes_i18n' => false,
        'audit_decisions' => false,
        'scoring_explanation' => false,
        'html_report' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'meta' => 'meta',
        'participants' => 'participants',
        'verdict' => 'verdict',
        'scores' => 'scores',
        'detections' => 'detections',
        'analysis' => 'analysis',
        'timeline' => 'timeline',
        'audio_event_model' => 'audio_event_model',
        'categories_summary' => 'categories_summary',
        'indexer' => 'indexer',
        'summary' => 'summary',
        'acoes_i18n' => 'acoes_i18n',
        'audit_decisions' => 'audit_decisions',
        'scoring_explanation' => 'scoring_explanation',
        'html_report' => 'html_report'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'meta' => 'setMeta',
        'participants' => 'setParticipants',
        'verdict' => 'setVerdict',
        'scores' => 'setScores',
        'detections' => 'setDetections',
        'analysis' => 'setAnalysis',
        'timeline' => 'setTimeline',
        'audio_event_model' => 'setAudioEventModel',
        'categories_summary' => 'setCategoriesSummary',
        'indexer' => 'setIndexer',
        'summary' => 'setSummary',
        'acoes_i18n' => 'setAcoesI18n',
        'audit_decisions' => 'setAuditDecisions',
        'scoring_explanation' => 'setScoringExplanation',
        'html_report' => 'setHtmlReport'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'meta' => 'getMeta',
        'participants' => 'getParticipants',
        'verdict' => 'getVerdict',
        'scores' => 'getScores',
        'detections' => 'getDetections',
        'analysis' => 'getAnalysis',
        'timeline' => 'getTimeline',
        'audio_event_model' => 'getAudioEventModel',
        'categories_summary' => 'getCategoriesSummary',
        'indexer' => 'getIndexer',
        'summary' => 'getSummary',
        'acoes_i18n' => 'getAcoesI18n',
        'audit_decisions' => 'getAuditDecisions',
        'scoring_explanation' => 'getScoringExplanation',
        'html_report' => 'getHtmlReport'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('meta', $data ?? [], null);
        $this->setIfExists('participants', $data ?? [], null);
        $this->setIfExists('verdict', $data ?? [], null);
        $this->setIfExists('scores', $data ?? [], null);
        $this->setIfExists('detections', $data ?? [], null);
        $this->setIfExists('analysis', $data ?? [], null);
        $this->setIfExists('timeline', $data ?? [], null);
        $this->setIfExists('audio_event_model', $data ?? [], null);
        $this->setIfExists('categories_summary', $data ?? [], null);
        $this->setIfExists('indexer', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('acoes_i18n', $data ?? [], null);
        $this->setIfExists('audit_decisions', $data ?? [], null);
        $this->setIfExists('scoring_explanation', $data ?? [], null);
        $this->setIfExists('html_report', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['meta'] === null) {
            $invalidProperties[] = "'meta' can't be null";
        }
        if ($this->container['participants'] === null) {
            $invalidProperties[] = "'participants' can't be null";
        }
        if ($this->container['verdict'] === null) {
            $invalidProperties[] = "'verdict' can't be null";
        }
        if ($this->container['scores'] === null) {
            $invalidProperties[] = "'scores' can't be null";
        }
        if ($this->container['detections'] === null) {
            $invalidProperties[] = "'detections' can't be null";
        }
        if ($this->container['analysis'] === null) {
            $invalidProperties[] = "'analysis' can't be null";
        }
        if ($this->container['timeline'] === null) {
            $invalidProperties[] = "'timeline' can't be null";
        }
        if ($this->container['audio_event_model'] === null) {
            $invalidProperties[] = "'audio_event_model' can't be null";
        }
        if ($this->container['categories_summary'] === null) {
            $invalidProperties[] = "'categories_summary' can't be null";
        }
        if ($this->container['indexer'] === null) {
            $invalidProperties[] = "'indexer' can't be null";
        }
        if ($this->container['summary'] === null) {
            $invalidProperties[] = "'summary' can't be null";
        }
        if ($this->container['acoes_i18n'] === null) {
            $invalidProperties[] = "'acoes_i18n' can't be null";
        }
        if ($this->container['audit_decisions'] === null) {
            $invalidProperties[] = "'audit_decisions' can't be null";
        }
        if ($this->container['scoring_explanation'] === null) {
            $invalidProperties[] = "'scoring_explanation' can't be null";
        }
        if ($this->container['html_report'] === null) {
            $invalidProperties[] = "'html_report' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets meta
     *
     * @return \FalaAI\Model\AuditoriaRiscoMetaV2
     */
    public function getMeta()
    {
        return $this->container['meta'];
    }

    /**
     * Sets meta
     *
     * @param \FalaAI\Model\AuditoriaRiscoMetaV2 $meta Identification + usage
     *
     * @return self
     */
    public function setMeta($meta)
    {
        if (is_null($meta)) {
            throw new \InvalidArgumentException('non-nullable meta cannot be null');
        }
        $this->container['meta'] = $meta;

        return $this;
    }

    /**
     * Gets participants
     *
     * @return \FalaAI\Model\AuditoriaRiscoParticipantsV2
     */
    public function getParticipants()
    {
        return $this->container['participants'];
    }

    /**
     * Sets participants
     *
     * @param \FalaAI\Model\AuditoriaRiscoParticipantsV2 $participants Participants/roles/direction
     *
     * @return self
     */
    public function setParticipants($participants)
    {
        if (is_null($participants)) {
            throw new \InvalidArgumentException('non-nullable participants cannot be null');
        }
        $this->container['participants'] = $participants;

        return $this;
    }

    /**
     * Gets verdict
     *
     * @return \FalaAI\Model\AuditoriaRiscoVerdictV2
     */
    public function getVerdict()
    {
        return $this->container['verdict'];
    }

    /**
     * Sets verdict
     *
     * @param \FalaAI\Model\AuditoriaRiscoVerdictV2 $verdict Verdict + level + applied actions
     *
     * @return self
     */
    public function setVerdict($verdict)
    {
        if (is_null($verdict)) {
            throw new \InvalidArgumentException('non-nullable verdict cannot be null');
        }
        $this->container['verdict'] = $verdict;

        return $this;
    }

    /**
     * Gets scores
     *
     * @return \FalaAI\Model\AuditoriaRiscoScoresV2
     */
    public function getScores()
    {
        return $this->container['scores'];
    }

    /**
     * Sets scores
     *
     * @param \FalaAI\Model\AuditoriaRiscoScoresV2 $scores Consolidated + per-participant scores
     *
     * @return self
     */
    public function setScores($scores)
    {
        if (is_null($scores)) {
            throw new \InvalidArgumentException('non-nullable scores cannot be null');
        }
        $this->container['scores'] = $scores;

        return $this;
    }

    /**
     * Gets detections
     *
     * @return \FalaAI\Model\AuditoriaRiscoDetectionsV2
     */
    public function getDetections()
    {
        return $this->container['detections'];
    }

    /**
     * Sets detections
     *
     * @param \FalaAI\Model\AuditoriaRiscoDetectionsV2 $detections violations/positives/client alerts
     *
     * @return self
     */
    public function setDetections($detections)
    {
        if (is_null($detections)) {
            throw new \InvalidArgumentException('non-nullable detections cannot be null');
        }
        $this->container['detections'] = $detections;

        return $this;
    }

    /**
     * Gets analysis
     *
     * @return \FalaAI\Model\AuditoriaRiscoAnalysisV2
     */
    public function getAnalysis()
    {
        return $this->container['analysis'];
    }

    /**
     * Sets analysis
     *
     * @param \FalaAI\Model\AuditoriaRiscoAnalysisV2 $analysis global_metrics + final_analysis + frameworks
     *
     * @return self
     */
    public function setAnalysis($analysis)
    {
        if (is_null($analysis)) {
            throw new \InvalidArgumentException('non-nullable analysis cannot be null');
        }
        $this->container['analysis'] = $analysis;

        return $this;
    }

    /**
     * Gets timeline
     *
     * @return \FalaAI\Model\AuditoriaRiscoTimelineV2
     */
    public function getTimeline()
    {
        return $this->container['timeline'];
    }

    /**
     * Sets timeline
     *
     * @param \FalaAI\Model\AuditoriaRiscoTimelineV2 $timeline turns_sentiment + audio_events + groups
     *
     * @return self
     */
    public function setTimeline($timeline)
    {
        if (is_null($timeline)) {
            throw new \InvalidArgumentException('non-nullable timeline cannot be null');
        }
        $this->container['timeline'] = $timeline;

        return $this;
    }

    /**
     * Gets audio_event_model
     *
     * @return \FalaAI\Model\AuditoriaRiscoAudioEventModelV2
     */
    public function getAudioEventModel()
    {
        return $this->container['audio_event_model'];
    }

    /**
     * Sets audio_event_model
     *
     * @param \FalaAI\Model\AuditoriaRiscoAudioEventModelV2 $audio_event_model MAC audio event semantics
     *
     * @return self
     */
    public function setAudioEventModel($audio_event_model)
    {
        if (is_null($audio_event_model)) {
            throw new \InvalidArgumentException('non-nullable audio_event_model cannot be null');
        }
        $this->container['audio_event_model'] = $audio_event_model;

        return $this;
    }

    /**
     * Gets categories_summary
     *
     * @return array<string,mixed>
     */
    public function getCategoriesSummary()
    {
        return $this->container['categories_summary'];
    }

    /**
     * Sets categories_summary
     *
     * @param array<string,mixed> $categories_summary Per-category summary (keyed by category)
     *
     * @return self
     */
    public function setCategoriesSummary($categories_summary)
    {
        if (is_null($categories_summary)) {
            throw new \InvalidArgumentException('non-nullable categories_summary cannot be null');
        }
        $this->container['categories_summary'] = $categories_summary;

        return $this;
    }

    /**
     * Gets indexer
     *
     * @return \FalaAI\Model\AuditoriaRiscoIndexerV2
     */
    public function getIndexer()
    {
        return $this->container['indexer'];
    }

    /**
     * Sets indexer
     *
     * @param \FalaAI\Model\AuditoriaRiscoIndexerV2 $indexer Suggested terms for bank
     *
     * @return self
     */
    public function setIndexer($indexer)
    {
        if (is_null($indexer)) {
            throw new \InvalidArgumentException('non-nullable indexer cannot be null');
        }
        $this->container['indexer'] = $indexer;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return \FalaAI\Model\AuditoriaRiscoSummaryV2
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param \FalaAI\Model\AuditoriaRiscoSummaryV2 $summary Executive summary counts
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets acoes_i18n
     *
     * @return array<string,mixed>
     */
    public function getAcoesI18n()
    {
        return $this->container['acoes_i18n'];
    }

    /**
     * Sets acoes_i18n
     *
     * @param array<string,mixed> $acoes_i18n Used actions i18n catalog (keyed by action)
     *
     * @return self
     */
    public function setAcoesI18n($acoes_i18n)
    {
        if (is_null($acoes_i18n)) {
            throw new \InvalidArgumentException('non-nullable acoes_i18n cannot be null');
        }
        $this->container['acoes_i18n'] = $acoes_i18n;

        return $this;
    }

    /**
     * Gets audit_decisions
     *
     * @return \FalaAI\Model\AuditoriaRiscoAuditDecisionsV2
     */
    public function getAuditDecisions()
    {
        return $this->container['audit_decisions'];
    }

    /**
     * Sets audit_decisions
     *
     * @param \FalaAI\Model\AuditoriaRiscoAuditDecisionsV2 $audit_decisions Risk origin + validator changes
     *
     * @return self
     */
    public function setAuditDecisions($audit_decisions)
    {
        if (is_null($audit_decisions)) {
            throw new \InvalidArgumentException('non-nullable audit_decisions cannot be null');
        }
        $this->container['audit_decisions'] = $audit_decisions;

        return $this;
    }

    /**
     * Gets scoring_explanation
     *
     * @return \FalaAI\Model\AuditoriaRiscoScoringExplanationV2
     */
    public function getScoringExplanation()
    {
        return $this->container['scoring_explanation'];
    }

    /**
     * Sets scoring_explanation
     *
     * @param \FalaAI\Model\AuditoriaRiscoScoringExplanationV2 $scoring_explanation Score composition explanation
     *
     * @return self
     */
    public function setScoringExplanation($scoring_explanation)
    {
        if (is_null($scoring_explanation)) {
            throw new \InvalidArgumentException('non-nullable scoring_explanation cannot be null');
        }
        $this->container['scoring_explanation'] = $scoring_explanation;

        return $this;
    }

    /**
     * Gets html_report
     *
     * @return string
     */
    public function getHtmlReport()
    {
        return $this->container['html_report'];
    }

    /**
     * Sets html_report
     *
     * @param string $html_report HTML report (base64 gzip)
     *
     * @return self
     */
    public function setHtmlReport($html_report)
    {
        if (is_null($html_report)) {
            throw new \InvalidArgumentException('non-nullable html_report cannot be null');
        }
        $this->container['html_report'] = $html_report;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


