<?php
/**
 * DiagnosticAnalysisMap
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;

use \ArrayAccess;
use \FalaAI\ObjectSerializer;

/**
 * DiagnosticAnalysisMap Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DiagnosticAnalysisMap implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'DiagnosticAnalysisMap';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'dialogue_summary' => '\FalaAI\Model\DiagnosticTextAnalysis',
        'contact_reason' => '\FalaAI\Model\DiagnosticTextAnalysis',
        'identified_action' => '\FalaAI\Model\DiagnosticCategoricalAnalysis',
        'identified_label' => '\FalaAI\Model\DiagnosticCategoricalAnalysis',
        'sentiment' => '\FalaAI\Model\DiagnosticCategoricalAnalysis',
        'participants_identified' => '\FalaAI\Model\ParticipantDiagnostic[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'dialogue_summary' => null,
        'contact_reason' => null,
        'identified_action' => null,
        'identified_label' => null,
        'sentiment' => null,
        'participants_identified' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'dialogue_summary' => false,
        'contact_reason' => false,
        'identified_action' => false,
        'identified_label' => false,
        'sentiment' => false,
        'participants_identified' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dialogue_summary' => 'dialogue_summary',
        'contact_reason' => 'contact_reason',
        'identified_action' => 'identified_action',
        'identified_label' => 'identified_label',
        'sentiment' => 'sentiment',
        'participants_identified' => 'participants_identified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dialogue_summary' => 'setDialogueSummary',
        'contact_reason' => 'setContactReason',
        'identified_action' => 'setIdentifiedAction',
        'identified_label' => 'setIdentifiedLabel',
        'sentiment' => 'setSentiment',
        'participants_identified' => 'setParticipantsIdentified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dialogue_summary' => 'getDialogueSummary',
        'contact_reason' => 'getContactReason',
        'identified_action' => 'getIdentifiedAction',
        'identified_label' => 'getIdentifiedLabel',
        'sentiment' => 'getSentiment',
        'participants_identified' => 'getParticipantsIdentified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('dialogue_summary', $data ?? [], null);
        $this->setIfExists('contact_reason', $data ?? [], null);
        $this->setIfExists('identified_action', $data ?? [], null);
        $this->setIfExists('identified_label', $data ?? [], null);
        $this->setIfExists('sentiment', $data ?? [], null);
        $this->setIfExists('participants_identified', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['dialogue_summary'] === null) {
            $invalidProperties[] = "'dialogue_summary' can't be null";
        }
        if ($this->container['contact_reason'] === null) {
            $invalidProperties[] = "'contact_reason' can't be null";
        }
        if ($this->container['identified_action'] === null) {
            $invalidProperties[] = "'identified_action' can't be null";
        }
        if ($this->container['identified_label'] === null) {
            $invalidProperties[] = "'identified_label' can't be null";
        }
        if ($this->container['sentiment'] === null) {
            $invalidProperties[] = "'sentiment' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dialogue_summary
     *
     * @return \FalaAI\Model\DiagnosticTextAnalysis
     */
    public function getDialogueSummary()
    {
        return $this->container['dialogue_summary'];
    }

    /**
     * Sets dialogue_summary
     *
     * @param \FalaAI\Model\DiagnosticTextAnalysis $dialogue_summary Detailed conversation summary
     *
     * @return self
     */
    public function setDialogueSummary($dialogue_summary)
    {
        if (is_null($dialogue_summary)) {
            throw new \InvalidArgumentException('non-nullable dialogue_summary cannot be null');
        }
        $this->container['dialogue_summary'] = $dialogue_summary;

        return $this;
    }

    /**
     * Gets contact_reason
     *
     * @return \FalaAI\Model\DiagnosticTextAnalysis
     */
    public function getContactReason()
    {
        return $this->container['contact_reason'];
    }

    /**
     * Sets contact_reason
     *
     * @param \FalaAI\Model\DiagnosticTextAnalysis $contact_reason Initial contact reason
     *
     * @return self
     */
    public function setContactReason($contact_reason)
    {
        if (is_null($contact_reason)) {
            throw new \InvalidArgumentException('non-nullable contact_reason cannot be null');
        }
        $this->container['contact_reason'] = $contact_reason;

        return $this;
    }

    /**
     * Gets identified_action
     *
     * @return \FalaAI\Model\DiagnosticCategoricalAnalysis
     */
    public function getIdentifiedAction()
    {
        return $this->container['identified_action'];
    }

    /**
     * Sets identified_action
     *
     * @param \FalaAI\Model\DiagnosticCategoricalAnalysis $identified_action Action taken / resolution
     *
     * @return self
     */
    public function setIdentifiedAction($identified_action)
    {
        if (is_null($identified_action)) {
            throw new \InvalidArgumentException('non-nullable identified_action cannot be null');
        }
        $this->container['identified_action'] = $identified_action;

        return $this;
    }

    /**
     * Gets identified_label
     *
     * @return \FalaAI\Model\DiagnosticCategoricalAnalysis
     */
    public function getIdentifiedLabel()
    {
        return $this->container['identified_label'];
    }

    /**
     * Sets identified_label
     *
     * @param \FalaAI\Model\DiagnosticCategoricalAnalysis $identified_label Theme classification
     *
     * @return self
     */
    public function setIdentifiedLabel($identified_label)
    {
        if (is_null($identified_label)) {
            throw new \InvalidArgumentException('non-nullable identified_label cannot be null');
        }
        $this->container['identified_label'] = $identified_label;

        return $this;
    }

    /**
     * Gets sentiment
     *
     * @return \FalaAI\Model\DiagnosticCategoricalAnalysis
     */
    public function getSentiment()
    {
        return $this->container['sentiment'];
    }

    /**
     * Sets sentiment
     *
     * @param \FalaAI\Model\DiagnosticCategoricalAnalysis $sentiment Predominant sentiment
     *
     * @return self
     */
    public function setSentiment($sentiment)
    {
        if (is_null($sentiment)) {
            throw new \InvalidArgumentException('non-nullable sentiment cannot be null');
        }
        $this->container['sentiment'] = $sentiment;

        return $this;
    }

    /**
     * Gets participants_identified
     *
     * @return \FalaAI\Model\ParticipantDiagnostic[]|null
     */
    public function getParticipantsIdentified()
    {
        return $this->container['participants_identified'];
    }

    /**
     * Sets participants_identified
     *
     * @param \FalaAI\Model\ParticipantDiagnostic[]|null $participants_identified Identified participants and roles (same field names as auditoria)
     *
     * @return self
     */
    public function setParticipantsIdentified($participants_identified)
    {
        if (is_null($participants_identified)) {
            throw new \InvalidArgumentException('non-nullable participants_identified cannot be null');
        }
        $this->container['participants_identified'] = $participants_identified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


