<?php
/**
 * EmailEvent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;
use \FalaAI\ObjectSerializer;

/**
 * EmailEvent Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailEvent
{
    /**
     * Possible values of this enum
     */
    public const SUBSCRIPTION_CREATED = 'subscription.created';

    public const AVULSO_COMPLETED = 'avulso.completed';

    public const SUBSCRIPTION_UPGRADED = 'subscription.upgraded';

    public const SUBSCRIPTION_DOWNGRADED = 'subscription.downgraded';

    public const SUBSCRIPTION_CANCELED = 'subscription.canceled';

    public const CREDITS_LOW = 'credits.low';

    public const CREDITS_EXHAUSTED = 'credits.exhausted';

    public const SUBSCRIPTION_RENEWED = 'subscription.renewed';

    public const PAYMENT_FAILED = 'payment.failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SUBSCRIPTION_CREATED,
            self::AVULSO_COMPLETED,
            self::SUBSCRIPTION_UPGRADED,
            self::SUBSCRIPTION_DOWNGRADED,
            self::SUBSCRIPTION_CANCELED,
            self::CREDITS_LOW,
            self::CREDITS_EXHAUSTED,
            self::SUBSCRIPTION_RENEWED,
            self::PAYMENT_FAILED
        ];
    }
}


