<?php
/**
 * TranscriptionResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;

use \ArrayAccess;
use \FalaAI\ObjectSerializer;

/**
 * TranscriptionResponse Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TranscriptionResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TranscriptionResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'object' => 'string',
        'model' => 'string',
        'filename' => 'string',
        'processed_at' => 'string',
        'usage' => '\FalaAI\Model\TranscriptionUsage',
        'language' => 'string',
        'language_confidence' => 'float',
        'duration_seconds' => 'float',
        'text' => 'string',
        'dialog' => 'string',
        'audio_events' => '\FalaAI\Model\AudioEvent[]',
        'event_types' => 'string[]',
        'word_count' => 'int',
        'input' => '\FalaAI\Model\AudioInputMeta',
        'client_reference_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'object' => null,
        'model' => null,
        'filename' => null,
        'processed_at' => null,
        'usage' => null,
        'language' => null,
        'language_confidence' => null,
        'duration_seconds' => null,
        'text' => null,
        'dialog' => null,
        'audio_events' => null,
        'event_types' => null,
        'word_count' => null,
        'input' => null,
        'client_reference_id' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'object' => false,
        'model' => false,
        'filename' => false,
        'processed_at' => false,
        'usage' => false,
        'language' => false,
        'language_confidence' => false,
        'duration_seconds' => false,
        'text' => false,
        'dialog' => false,
        'audio_events' => false,
        'event_types' => false,
        'word_count' => false,
        'input' => false,
        'client_reference_id' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'object' => 'object',
        'model' => 'model',
        'filename' => 'filename',
        'processed_at' => 'processed_at',
        'usage' => 'usage',
        'language' => 'language',
        'language_confidence' => 'language_confidence',
        'duration_seconds' => 'duration_seconds',
        'text' => 'text',
        'dialog' => 'dialog',
        'audio_events' => 'audio_events',
        'event_types' => 'event_types',
        'word_count' => 'word_count',
        'input' => 'input',
        'client_reference_id' => 'client_reference_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'object' => 'setObject',
        'model' => 'setModel',
        'filename' => 'setFilename',
        'processed_at' => 'setProcessedAt',
        'usage' => 'setUsage',
        'language' => 'setLanguage',
        'language_confidence' => 'setLanguageConfidence',
        'duration_seconds' => 'setDurationSeconds',
        'text' => 'setText',
        'dialog' => 'setDialog',
        'audio_events' => 'setAudioEvents',
        'event_types' => 'setEventTypes',
        'word_count' => 'setWordCount',
        'input' => 'setInput',
        'client_reference_id' => 'setClientReferenceId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'object' => 'getObject',
        'model' => 'getModel',
        'filename' => 'getFilename',
        'processed_at' => 'getProcessedAt',
        'usage' => 'getUsage',
        'language' => 'getLanguage',
        'language_confidence' => 'getLanguageConfidence',
        'duration_seconds' => 'getDurationSeconds',
        'text' => 'getText',
        'dialog' => 'getDialog',
        'audio_events' => 'getAudioEvents',
        'event_types' => 'getEventTypes',
        'word_count' => 'getWordCount',
        'input' => 'getInput',
        'client_reference_id' => 'getClientReferenceId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('object', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('filename', $data ?? [], null);
        $this->setIfExists('processed_at', $data ?? [], null);
        $this->setIfExists('usage', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('language_confidence', $data ?? [], null);
        $this->setIfExists('duration_seconds', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('dialog', $data ?? [], null);
        $this->setIfExists('audio_events', $data ?? [], null);
        $this->setIfExists('event_types', $data ?? [], null);
        $this->setIfExists('word_count', $data ?? [], null);
        $this->setIfExists('input', $data ?? [], null);
        $this->setIfExists('client_reference_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['object'] === null) {
            $invalidProperties[] = "'object' can't be null";
        }
        if ($this->container['model'] === null) {
            $invalidProperties[] = "'model' can't be null";
        }
        if ($this->container['filename'] === null) {
            $invalidProperties[] = "'filename' can't be null";
        }
        if ($this->container['processed_at'] === null) {
            $invalidProperties[] = "'processed_at' can't be null";
        }
        if ($this->container['usage'] === null) {
            $invalidProperties[] = "'usage' can't be null";
        }
        if ($this->container['language'] === null) {
            $invalidProperties[] = "'language' can't be null";
        }
        if ($this->container['duration_seconds'] === null) {
            $invalidProperties[] = "'duration_seconds' can't be null";
        }
        if ($this->container['text'] === null) {
            $invalidProperties[] = "'text' can't be null";
        }
        if ($this->container['dialog'] === null) {
            $invalidProperties[] = "'dialog' can't be null";
        }
        if ($this->container['audio_events'] === null) {
            $invalidProperties[] = "'audio_events' can't be null";
        }
        if ($this->container['event_types'] === null) {
            $invalidProperties[] = "'event_types' can't be null";
        }
        if ($this->container['word_count'] === null) {
            $invalidProperties[] = "'word_count' can't be null";
        }
        if ($this->container['input'] === null) {
            $invalidProperties[] = "'input' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique transcription identifier. Prefix 'tr-' followed by UUID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets object
     *
     * @return string
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string $object Returned object type. Always 'transcription'
     *
     * @return self
     */
    public function setObject($object)
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string $model Model used for transcription. Ex: 'falaai-transcribe-1'
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            throw new \InvalidArgumentException('non-nullable model cannot be null');
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets filename
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string $filename Original audio file name uploaded
     *
     * @return self
     */
    public function setFilename($filename)
    {
        if (is_null($filename)) {
            throw new \InvalidArgumentException('non-nullable filename cannot be null');
        }
        $this->container['filename'] = $filename;

        return $this;
    }

    /**
     * Gets processed_at
     *
     * @return string
     */
    public function getProcessedAt()
    {
        return $this->container['processed_at'];
    }

    /**
     * Sets processed_at
     *
     * @param string $processed_at Processing datetime in ISO 8601 UTC format
     *
     * @return self
     */
    public function setProcessedAt($processed_at)
    {
        if (is_null($processed_at)) {
            throw new \InvalidArgumentException('non-nullable processed_at cannot be null');
        }
        $this->container['processed_at'] = $processed_at;

        return $this;
    }

    /**
     * Gets usage
     *
     * @return \FalaAI\Model\TranscriptionUsage
     */
    public function getUsage()
    {
        return $this->container['usage'];
    }

    /**
     * Sets usage
     *
     * @param \FalaAI\Model\TranscriptionUsage $usage Usage and processing information
     *
     * @return self
     */
    public function setUsage($usage)
    {
        if (is_null($usage)) {
            throw new \InvalidArgumentException('non-nullable usage cannot be null');
        }
        $this->container['usage'] = $usage;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string $language ISO 639-3 language code detected in audio. Ex: 'por' (Portuguese), 'eng' (English), 'spa' (Spanish)
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets language_confidence
     *
     * @return float|null
     */
    public function getLanguageConfidence()
    {
        return $this->container['language_confidence'];
    }

    /**
     * Sets language_confidence
     *
     * @param float|null $language_confidence Language detection confidence level (0.0 to 1.0). Higher is more reliable
     *
     * @return self
     */
    public function setLanguageConfidence($language_confidence)
    {
        if (is_null($language_confidence)) {
            throw new \InvalidArgumentException('non-nullable language_confidence cannot be null');
        }
        $this->container['language_confidence'] = $language_confidence;

        return $this;
    }

    /**
     * Gets duration_seconds
     *
     * @return float
     */
    public function getDurationSeconds()
    {
        return $this->container['duration_seconds'];
    }

    /**
     * Sets duration_seconds
     *
     * @param float $duration_seconds Total audio duration in seconds
     *
     * @return self
     */
    public function setDurationSeconds($duration_seconds)
    {
        if (is_null($duration_seconds)) {
            throw new \InvalidArgumentException('non-nullable duration_seconds cannot be null');
        }
        $this->container['duration_seconds'] = $duration_seconds;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text Full transcription as plain text, including audio events in brackets
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets dialog
     *
     * @return string
     */
    public function getDialog()
    {
        return $this->container['dialog'];
    }

    /**
     * Sets dialog
     *
     * @param string $dialog Turn-by-turn formatted transcript with speaker identification and start/end timestamps
     *
     * @return self
     */
    public function setDialog($dialog)
    {
        if (is_null($dialog)) {
            throw new \InvalidArgumentException('non-nullable dialog cannot be null');
        }
        $this->container['dialog'] = $dialog;

        return $this;
    }

    /**
     * Gets audio_events
     *
     * @return \FalaAI\Model\AudioEvent[]
     */
    public function getAudioEvents()
    {
        return $this->container['audio_events'];
    }

    /**
     * Sets audio_events
     *
     * @param \FalaAI\Model\AudioEvent[] $audio_events List of detected audio events (laughs, sighs, pauses, etc) with timestamps and duration
     *
     * @return self
     */
    public function setAudioEvents($audio_events)
    {
        if (is_null($audio_events)) {
            throw new \InvalidArgumentException('non-nullable audio_events cannot be null');
        }
        $this->container['audio_events'] = $audio_events;

        return $this;
    }

    /**
     * Gets event_types
     *
     * @return string[]
     */
    public function getEventTypes()
    {
        return $this->container['event_types'];
    }

    /**
     * Sets event_types
     *
     * @param string[] $event_types Unique audio event types found in transcription, alphabetically sorted
     *
     * @return self
     */
    public function setEventTypes($event_types)
    {
        if (is_null($event_types)) {
            throw new \InvalidArgumentException('non-nullable event_types cannot be null');
        }
        $this->container['event_types'] = $event_types;

        return $this;
    }

    /**
     * Gets word_count
     *
     * @return int
     */
    public function getWordCount()
    {
        return $this->container['word_count'];
    }

    /**
     * Sets word_count
     *
     * @param int $word_count Total number of recognized words in transcription
     *
     * @return self
     */
    public function setWordCount($word_count)
    {
        if (is_null($word_count)) {
            throw new \InvalidArgumentException('non-nullable word_count cannot be null');
        }
        $this->container['word_count'] = $word_count;

        return $this;
    }

    /**
     * Gets input
     *
     * @return \FalaAI\Model\AudioInputMeta
     */
    public function getInput()
    {
        return $this->container['input'];
    }

    /**
     * Sets input
     *
     * @param \FalaAI\Model\AudioInputMeta $input Metadados do arquivo de audio enviado (duracao, formato, codec, sample rate, canais)
     *
     * @return self
     */
    public function setInput($input)
    {
        if (is_null($input)) {
            throw new \InvalidArgumentException('non-nullable input cannot be null');
        }
        $this->container['input'] = $input;

        return $this;
    }

    /**
     * Gets client_reference_id
     *
     * @return string|null
     */
    public function getClientReferenceId()
    {
        return $this->container['client_reference_id'];
    }

    /**
     * Sets client_reference_id
     *
     * @param string|null $client_reference_id Client-supplied ID echoed verbatim (if provided in request)
     *
     * @return self
     */
    public function setClientReferenceId($client_reference_id)
    {
        if (is_null($client_reference_id)) {
            throw new \InvalidArgumentException('non-nullable client_reference_id cannot be null');
        }
        $this->container['client_reference_id'] = $client_reference_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


