<?php
/**
 * WebhookEvent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;
use \FalaAI\ObjectSerializer;

/**
 * WebhookEvent Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookEvent
{
    /**
     * Possible values of this enum
     */
    public const SUBSCRIPTION_CREATED = 'subscription.created';

    public const AVULSO_COMPLETED = 'avulso.completed';

    public const SUBSCRIPTION_UPGRADED = 'subscription.upgraded';

    public const SUBSCRIPTION_DOWNGRADED = 'subscription.downgraded';

    public const SUBSCRIPTION_CANCELED = 'subscription.canceled';

    public const CREDITS_LOW = 'credits.low';

    public const CREDITS_EXHAUSTED = 'credits.exhausted';

    public const SUBSCRIPTION_RENEWED = 'subscription.renewed';

    public const SUBSCRIPTION_EXPIRED = 'subscription.expired';

    public const PAYMENT_FAILED = 'payment.failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SUBSCRIPTION_CREATED,
            self::AVULSO_COMPLETED,
            self::SUBSCRIPTION_UPGRADED,
            self::SUBSCRIPTION_DOWNGRADED,
            self::SUBSCRIPTION_CANCELED,
            self::CREDITS_LOW,
            self::CREDITS_EXHAUSTED,
            self::SUBSCRIPTION_RENEWED,
            self::SUBSCRIPTION_EXPIRED,
            self::PAYMENT_FAILED
        ];
    }
}


