<?php
/**
 * WhatsappConversation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FalaAI\Model;

use \ArrayAccess;
use \FalaAI\ObjectSerializer;

/**
 * WhatsappConversation Class Doc Comment
 *
 * @category Class
 * @package  FalaAI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WhatsappConversation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'WhatsappConversation';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'conversation_id' => 'string',
        'first_at' => 'string',
        'last_at' => 'string',
        'duration_seconds' => 'float',
        'speakers' => '\FalaAI\Model\WhatsappSpeaker[]',
        'dialog' => 'string',
        'message_count' => 'int',
        'characters' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'conversation_id' => null,
        'first_at' => null,
        'last_at' => null,
        'duration_seconds' => null,
        'speakers' => null,
        'dialog' => null,
        'message_count' => null,
        'characters' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'conversation_id' => false,
        'first_at' => false,
        'last_at' => false,
        'duration_seconds' => false,
        'speakers' => false,
        'dialog' => false,
        'message_count' => false,
        'characters' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'conversation_id' => 'conversation_id',
        'first_at' => 'first_at',
        'last_at' => 'last_at',
        'duration_seconds' => 'duration_seconds',
        'speakers' => 'speakers',
        'dialog' => 'dialog',
        'message_count' => 'message_count',
        'characters' => 'characters'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'conversation_id' => 'setConversationId',
        'first_at' => 'setFirstAt',
        'last_at' => 'setLastAt',
        'duration_seconds' => 'setDurationSeconds',
        'speakers' => 'setSpeakers',
        'dialog' => 'setDialog',
        'message_count' => 'setMessageCount',
        'characters' => 'setCharacters'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'conversation_id' => 'getConversationId',
        'first_at' => 'getFirstAt',
        'last_at' => 'getLastAt',
        'duration_seconds' => 'getDurationSeconds',
        'speakers' => 'getSpeakers',
        'dialog' => 'getDialog',
        'message_count' => 'getMessageCount',
        'characters' => 'getCharacters'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('conversation_id', $data ?? [], null);
        $this->setIfExists('first_at', $data ?? [], null);
        $this->setIfExists('last_at', $data ?? [], null);
        $this->setIfExists('duration_seconds', $data ?? [], null);
        $this->setIfExists('speakers', $data ?? [], null);
        $this->setIfExists('dialog', $data ?? [], null);
        $this->setIfExists('message_count', $data ?? [], null);
        $this->setIfExists('characters', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['conversation_id'] === null) {
            $invalidProperties[] = "'conversation_id' can't be null";
        }
        if ($this->container['first_at'] === null) {
            $invalidProperties[] = "'first_at' can't be null";
        }
        if ($this->container['last_at'] === null) {
            $invalidProperties[] = "'last_at' can't be null";
        }
        if ($this->container['duration_seconds'] === null) {
            $invalidProperties[] = "'duration_seconds' can't be null";
        }
        if ($this->container['speakers'] === null) {
            $invalidProperties[] = "'speakers' can't be null";
        }
        if ($this->container['dialog'] === null) {
            $invalidProperties[] = "'dialog' can't be null";
        }
        if ($this->container['message_count'] === null) {
            $invalidProperties[] = "'message_count' can't be null";
        }
        if ($this->container['characters'] === null) {
            $invalidProperties[] = "'characters' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets conversation_id
     *
     * @return string
     */
    public function getConversationId()
    {
        return $this->container['conversation_id'];
    }

    /**
     * Sets conversation_id
     *
     * @param string $conversation_id Conversation identifier in the batch
     *
     * @return self
     */
    public function setConversationId($conversation_id)
    {
        if (is_null($conversation_id)) {
            throw new \InvalidArgumentException('non-nullable conversation_id cannot be null');
        }
        $this->container['conversation_id'] = $conversation_id;

        return $this;
    }

    /**
     * Gets first_at
     *
     * @return string
     */
    public function getFirstAt()
    {
        return $this->container['first_at'];
    }

    /**
     * Sets first_at
     *
     * @param string $first_at Real start (wall-clock, ISO)
     *
     * @return self
     */
    public function setFirstAt($first_at)
    {
        if (is_null($first_at)) {
            throw new \InvalidArgumentException('non-nullable first_at cannot be null');
        }
        $this->container['first_at'] = $first_at;

        return $this;
    }

    /**
     * Gets last_at
     *
     * @return string
     */
    public function getLastAt()
    {
        return $this->container['last_at'];
    }

    /**
     * Sets last_at
     *
     * @param string $last_at Real end (wall-clock, ISO)
     *
     * @return self
     */
    public function setLastAt($last_at)
    {
        if (is_null($last_at)) {
            throw new \InvalidArgumentException('non-nullable last_at cannot be null');
        }
        $this->container['last_at'] = $last_at;

        return $this;
    }

    /**
     * Gets duration_seconds
     *
     * @return float
     */
    public function getDurationSeconds()
    {
        return $this->container['duration_seconds'];
    }

    /**
     * Sets duration_seconds
     *
     * @param float $duration_seconds (last - first) + last turn duration
     *
     * @return self
     */
    public function setDurationSeconds($duration_seconds)
    {
        if (is_null($duration_seconds)) {
            throw new \InvalidArgumentException('non-nullable duration_seconds cannot be null');
        }
        $this->container['duration_seconds'] = $duration_seconds;

        return $this;
    }

    /**
     * Gets speakers
     *
     * @return \FalaAI\Model\WhatsappSpeaker[]
     */
    public function getSpeakers()
    {
        return $this->container['speakers'];
    }

    /**
     * Sets speakers
     *
     * @param \FalaAI\Model\WhatsappSpeaker[] $speakers Speakers of THIS conversation (dynamic)
     *
     * @return self
     */
    public function setSpeakers($speakers)
    {
        if (is_null($speakers)) {
            throw new \InvalidArgumentException('non-nullable speakers cannot be null');
        }
        $this->container['speakers'] = $speakers;

        return $this;
    }

    /**
     * Gets dialog
     *
     * @return string
     */
    public function getDialog()
    {
        return $this->container['dialog'];
    }

    /**
     * Sets dialog
     *
     * @param string $dialog Lines 'Speaker N: [HH:MM:SS.mmm - HH:MM:SS.mmm] text' (real offset)
     *
     * @return self
     */
    public function setDialog($dialog)
    {
        if (is_null($dialog)) {
            throw new \InvalidArgumentException('non-nullable dialog cannot be null');
        }
        $this->container['dialog'] = $dialog;

        return $this;
    }

    /**
     * Gets message_count
     *
     * @return int
     */
    public function getMessageCount()
    {
        return $this->container['message_count'];
    }

    /**
     * Sets message_count
     *
     * @param int $message_count Number of messages
     *
     * @return self
     */
    public function setMessageCount($message_count)
    {
        if (is_null($message_count)) {
            throw new \InvalidArgumentException('non-nullable message_count cannot be null');
        }
        $this->container['message_count'] = $message_count;

        return $this;
    }

    /**
     * Gets characters
     *
     * @return int
     */
    public function getCharacters()
    {
        return $this->container['characters'];
    }

    /**
     * Sets characters
     *
     * @param int $characters Total characters of the conversation
     *
     * @return self
     */
    public function setCharacters($characters)
    {
        if (is_null($characters)) {
            throw new \InvalidArgumentException('non-nullable characters cannot be null');
        }
        $this->container['characters'] = $characters;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


